--- 
- 
  hosts: jeff_pis
  become: true
  become_method: sudo
  become_user: root
  tasks:

    - name: Ensure git is installed 
      apt:
        name: git
        state: present

    - name: Ensure pip3 is installed 
      apt:
        name: python3-pip 
        state: present

    -  name: Get gonet3 repo from GitHub
       git: 
        dest: /home/pi/test
        repo: "https://github.com/Wied58/gonet3.git"
        update: yes
        force: yes

    - name: Change owevership and permissions
      file:
        path: /home/pi/test/
        state: directory
        owner: pi 
        group: pi
        # when specifying mode using octal numbers, add a leading 0
        mode: 0755
        recurse: yes
